config/routes.rb
Rails.application.routes.draw do
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  resources :cards

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]
  after_action :notify_clients, only: [:create, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def notify_clients
    ActionCable.server.broadcast 'messages',
      {
        action: action_name,
        card: @card
      }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.fetch(:card, {}).permit(:title, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    ActionCable.server.broadcast 'messages',
                                 message: 'One more joined us',
                                 user: 'OMG! He is Anon Mouse!
'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cards/_form.html.haml
= form_for(card) do |f|
  - if card.errors.any?
    #error_explanation
      %h2
        = pluralize(card.errors.count, 'error')
        prohibited this card from being saved:
      %ul
        - card.errors.full_messages.each do |message|
          %li= message

  #fields
    %h4 Title
    = f.text_field :title

    %h4 Description
    = f.text_area :description

  .actions
    = f.submit

app/views/cards/edit.html.haml
%h1 Editing Card
= render 'form', card: @card
= link_to 'Show', @card
|
= link_to 'Back', cards_path

app/views/cards/index.html.haml
%p#notice= notice
%h1 Cards
%table
  %thead
    %tr
      %th{:colspan => '5'}
  %tbody
    - @cards.each do |card|
      %tr
        %td
          %strong= card.title
        %td= card.description
        %td= link_to 'Show', card
        %td= link_to 'Edit', edit_card_path(card)
        %td= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Card', new_card_path

app/views/cards/new.html.haml
%h1 New Card
= render 'form', card: @card
= link_to 'Back', cards_path

app/views/cards/show.html.haml
%p#notice= notice

%h3= @card.title

.description= @card.description

= link_to 'Edit', edit_card_path(@card)
|
= link_to 'Back', cards_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Retrotool
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/welcome/index.haml
%h1 Yay
%h3 I like to move it move it!

%h4 Messages start
.hint Hey! Open this page in another tab and get back to see MAGICK!
#messages

%h4 Messages end